made index and show view
Tech-Nayuta/cta_reactive_master pull request #2
Opened 2021-01-08 05:39 UTC by Tech-Nayuta

## 関連するIssues

## 行ったこと
- 一覧画面と詳細画面の作成
    一覧画面
　　APIのフェッチしたデータを一覧表示
　　アラート機能
　　リフレッシュ機能

　詳細画面
　　フェッチしたデータのリンクからWKWebViewを使いウェブビューを表示

## 変更内容

| Before | After |
| --- | --- |
|  |  |

## 参考
- 

## その他 補足

2021-01-08 10:17 UTC, takumaosada commented on .gitignore
> +*/xcodeproj/Frameworks
```suggestion
*.xcodeproj/Frameworks
```
じゃないと意味ない気がする

2021-01-08 10:17 UTC, takumaosada commented on .gitignore
> +/DerivedData
今回もこれしないとダメだった？

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Resources/Base.lproj/LaunchScreen.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
不要な差分な気がしたけどこれは何かの目的があった感じ？

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/ConvenientCode(unused).swift
> +
不要なファイルなので消去してもらえると:pray:

2021-01-08 10:17 UTC, takumaosada commented on Podfile
> +  pod 'Kingfisher'
元々画像処理用にはNukeが入ってるので
- Nukeを利用する場合はKingfisherを抜いて欲しい
- Kingfisherを利用する場合はNukeを抜いて欲しい

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/DetailViewController.swift
> +class DetailViewController: UIViewController {
ごめんこれはちゃんとした共有ができてなかったんだけど詳細画面を実際に作成するのではなく
https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller を利用して欲しいです

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    @IBOutlet weak var tableView: UITableView!{
privateつけれそう

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +import Foundation
nits UIKitはFoundationも含んでいるので追加でimportする必要はないで

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
private以下略

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    fileprivate var articles:[Article] = []
privateでも良さそう？

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/Extension/UIAlertController+Retry.swift
> +extension UIAlertController {
UIAlertControllerのextensionである必要がなさそうなのでUIViewControllerとかで良さそう？

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +                    }
改行の仕方に違和感を感じる..?

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    }
これ必要だった？

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        }
ditto

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/SceneDelegate.swift
> +//            window.rootViewController = HomeViewController(nibName: nil, bundle: nil)
消しちゃっていいかも

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +        titleLabel.text = article.title ?? ""
```suggestion
        titleLabel.text = article.title
```
でも同じになると思う

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +        let publishedAt = article.publishedAt ?? ""
ditto

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +        }
ditto

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +    }
何もしてない場合は消してしまって大丈夫

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +    }
ナイスぅ

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +class NewsTableViewCell: UITableViewCell {
final付けれそう

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +    @IBOutlet weak var iconImageView: UIImageView!
private付けれそう

2021-01-08 10:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +        let publishedAt = article.publishedAt ?? ""
日付のformatの仕方結構周りくどい方法使ってそうなのでもう少し調べてみてもいいかも

2021-01-09 05:09 UTC, Tech-Nayuta commented on .gitignore
> +/DerivedData
そうですね、、！
Argument list too longとなりcommitができませんでした!

2021-01-09 05:11 UTC, Tech-Nayuta commented on CtaReactiveMaster/Resources/Base.lproj/LaunchScreen.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
Navigation関連でちょっといじったので差分がでてますが特に目的はありません！

2021-01-09 05:22 UTC, Tech-Nayuta commented on Podfile
> +  pod 'Kingfisher'
了解です！
Nukeを抜いておきます

2021-01-09 05:24 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/DetailViewController.swift
> +class DetailViewController: UIViewController {
了解です！

2021-01-09 05:26 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    }
なくても大丈夫でした！

2021-01-09 06:06 UTC, takumaosada commented on CtaReactiveMaster/Resources/Base.lproj/LaunchScreen.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
基本的にいじるようなファイルではないので目的がなければ差分ないようにしてほしい

2021-01-09 06:11 UTC, takumaosada commented on Podfile
> +  pod 'Kingfisher'
ちなみに今回kingfisherを利用しているのは理由があったりする？(ないといけないわけではない)

2021-01-09 06:50 UTC, ry-itto commented on .gitignore
> +/DerivedData
これなんでなんだろうなー
普通はこの記述いらないのだけど

2021-01-09 06:52 UTC, ry-itto commented on .gitignore
> +*/xcodeproj/Frameworks
ちなみにこれはなんで追加したんだろう🤔

2021-01-09 07:07 UTC, ry-itto requested changes
レビューしました🙏

2021-01-09 07:07 UTC, ry-itto commented on CtaReactiveMaster/Sources/Extension/Date+Format.swift
> +    func YYYYMMddString() -> String {
関数呼び出しってよりもcomputed prorertyでやる方が直感的かな

2021-01-09 07:07 UTC, ry-itto commented on CtaReactiveMaster/Sources/Extension/DateUtils.swift
> +        guard let modifiedDate = Calendar.current.date(byAdding: .hour, value:9, to: date)
timezoneとかいじっていい感じにできなかったっけ
9時間足してるところ

2021-01-09 07:07 UTC, ry-itto commented on CtaReactiveMaster/Sources/Extension/DateUtils.swift
> +        formatter.calendar = Calendar(identifier: .gregorian)
ここgregorianなのって理由あったりする？

2021-01-09 07:07 UTC, ry-itto commented on CtaReactiveMaster/Sources/Extension/DateUtils.swift
> +        let formatter: DateFormatter = DateFormatter()
型がわかりきってるのでちょっと冗長かな
```suggestion
        let formatter = DateFormatter()
```

2021-01-09 07:07 UTC, ry-itto commented on CtaReactiveMaster/Sources/Extension/DateUtils.swift
> +        let formatter: DateFormatter = DateFormatter()
型がわかってるのでちょっと冗長
```suggestion
        let formatter = DateFormatter()
```

2021-01-09 07:07 UTC, ry-itto commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +                    guard let unwrappedData = data
```suggestion
                    guard let data = data
```
名前変えなくても大丈夫だで

2021-01-09 07:07 UTC, ry-itto commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    private func fetchNewsAPI(){
selfをoptional chainingして使用している箇所が多いので、guard文で先にアンラップしてもいいかも

2021-01-09 07:07 UTC, ry-itto commented on CtaReactiveMaster/Sources/Model/NewsApiJSON.swift
> +struct JsonData: Decodable{
名前がすごく抽象的なので、別の名前に変えたいかな🤔

2021-01-09 07:07 UTC, ry-itto commented on CtaReactiveMaster/Sources/Model/NewsApiJSON.swift
> +import UIKit
UIKitをimportする必要はないので、Foundationを代わりにimportしよう

2021-01-09 07:07 UTC, ry-itto commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +        guard let unwrappedDate = date else{
ditto

2021-01-09 07:07 UTC, ry-itto commented on Podfile
> +  pod 'SwiftyJSON'
Codable使ってるので不要かな

2021-01-11 02:38 UTC, nayutaroo commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        }
92行目のurlで使います！

2021-01-11 02:38 UTC, Tech-Nayuta commented on CtaReactiveMaster/Resources/Base.lproj/LaunchScreen.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
わかりました！
！

2021-01-11 02:38 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/ConvenientCode(unused).swift
> +
わかりました！
ちなみにこのファイルではスニペットとして再利用できるようコメントでコードを残していたのですがこういうのって普段どういう風に残してますか？

2021-01-11 02:41 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +    }
りょうかいです！

2021-01-11 02:49 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +    @IBOutlet weak var iconImageView: UIImageView!
つけました！

2021-01-11 02:49 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +class NewsTableViewCell: UITableViewCell {
つけました！
！

2021-01-11 02:52 UTC, Tech-Nayuta commented on Podfile
> +  pod 'SwiftyJSON'
変更しました！
！

2021-01-11 02:52 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +        guard let unwrappedDate = date else{
変更しました！

2021-01-11 02:53 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Model/NewsApiJSON.swift
> +import UIKit
へんこうしました！

2021-01-11 02:53 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Extension/DateUtils.swift
> +        let formatter: DateFormatter = DateFormatter()
変更しました！

2021-01-11 02:56 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Extension/DateUtils.swift
> +        formatter.calendar = Calendar(identifier: .gregorian)
ここはブログを参考にしてます！
とくに理由はないです！

2021-01-11 02:58 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Extension/Date+Format.swift
> +    func YYYYMMddString() -> String {
あれ、すみませんこのファイル使用していないので消しておきます...！
ファイル消去するときはRemove referenceではなくMove To Trashを選ばないとコミットされちゃうんですね（笑）

2021-01-11 03:07 UTC, takumaosada commented
pushできてなさそう...?

2021-01-11 03:56 UTC, takumaosada commented on Podfile
> +  pod 'Kingfisher'
そもそもデフォルトでnuke入れているのはnukeがすごく優秀という理由があるのでこれ読んでみてもいいかも
https://qiita.com/hcrane/items/422811dfc18ae919f8a4

2021-01-11 03:57 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        }
改行の仕方の話

2021-01-11 03:59 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        }
```suggestion
        guard let url = articles[indexPath.row].url else { return }
```
```suggestion
        guard let url = articles[indexPath.row].url else { 
             return 
         }
```
どっちかに修正してほしい。他のguard文使ってる箇所も。

2021-01-11 04:00 UTC, takumaosada commented on CtaReactiveMaster/Sources/ConvenientCode(unused).swift
> +
notionとかメモとか自分だけが見れる場所に保存してるかな

2021-01-12 00:25 UTC, Tech-Nayuta reviewed
修正が完了しました！

2021-01-12 00:25 UTC, nayutaroo commented on Podfile
> +  pod 'Kingfisher'
特にないです！
ネイティブブートキャンプでは画像処理にkingfisherを使用していたので今回もKingfisherを使用してます！

2021-01-12 01:13 UTC, takumaosada requested changes

2021-01-12 01:13 UTC, takumaosada commented on .gitignore
> +*/xcodeproj/Frameworks
これの対応忘れてそう

2021-01-12 01:13 UTC, takumaosada commented on CtaReactiveMaster/Resources/Base.lproj/LaunchScreen.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
これも忘れてそう

2021-01-12 01:13 UTC, takumaosada commented on CtaReactiveMaster/Sources/DetailViewController.swift
> +class DetailViewController: UIViewController {
このファイルもう使ってないはずなので消して良さそう？

2021-01-12 01:13 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        activityIndicator.stopAnimating()
これstartanimatingした直後にstopanimatingしてしまってるのでactivityindicator動いてないんじゃない？

2021-01-12 01:13 UTC, takumaosada commented on CtaReactiveMaster/Sources/Model/NewsApiJSON.swift
> +struct NewsJSON: Decodable{
この方自体はJSONと何も関係がないはずなので命名変えた方が良さそう

2021-01-12 01:13 UTC, takumaosada commented on CtaReactiveMaster/Sources/SceneDelegate.swift
> +            window.rootViewController = UINavigationController(rootViewController: HomeViewController(nibName: nil, bundle: nil))
appDelegateとsceneDelegateでUInavigationControllerを使うかどうか揃えた方が良さそう

2021-01-12 01:13 UTC, takumaosada commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +        guard let url = URL(string: article.urlToImage ?? "") else{ return }
guard文を関数の途中で出現されるのはあんまり可読性よくないのでこの場合はif文を使った方がいいと思う

2021-01-12 01:18 UTC, Tech-Nayuta commented on CtaReactiveMaster/Resources/Base.lproj/LaunchScreen.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
これ元に戻すにはどうすればいいですか、、？

2021-01-12 01:18 UTC, Tech-Nayuta commented on .gitignore
> +*/xcodeproj/Frameworks
忘れてました🙇‍♂️

2021-01-12 01:39 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        activityIndicator.stopAnimating()
ほんまですね、動いでませんでした笑
fetchNewsAPI()の処理が終了するまでにstopAnimating呼び出されてしまうんですね笑

2021-01-12 01:52 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/SceneDelegate.swift
> +            window.rootViewController = UINavigationController(rootViewController: HomeViewController(nibName: nil, bundle: nil))
揃えました！
！

2021-01-12 01:52 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +        guard let url = URL(string: article.urlToImage ?? "") else{ return }
了解です

2021-01-12 01:52 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Model/NewsApiJSON.swift
> +struct NewsJSON: Decodable{
了解です

2021-01-13 08:37 UTC, takumaosada requested changes

2021-01-13 08:37 UTC, takumaosada commented on CtaReactiveMaster/Resources/Base.lproj/LaunchScreen.storyboard
> +    <device id="retina6_1" orientation="portrait" appearance="light"/>
gitでどうにか頑張るとかでもいいし`main`ブランチからソースをコピペするとかで対応して欲しい

2021-01-13 08:37 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +                        let jsonData = try jsonDecoder.decode(News.self, from: data)
jsonDataって変数名は少しおかしいかも(元がjsonでそれを型に落とし込んだものなので)

2021-01-13 08:37 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +                    break
これって必要？

2021-01-13 08:37 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +            if isRefreshing{
```suggestion
            if isRefreshing {
```

2021-01-13 08:37 UTC, takumaosada commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +            if let url = URL(string: article.urlToImage ?? "") { setImage(with: url) }
urlToImageはpublishedAtと関係ないのでif文の中でこのif文展開する必要はなさそう？

2021-01-14 04:06 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +            if let url = URL(string: article.urlToImage ?? "") { setImage(with: url) }
ですね笑

2021-01-14 04:09 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +                    break
break文のことですよね！いえ、いりません笑
C言語の癖です笑

2021-01-14 04:10 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +            if isRefreshing{
完了

2021-01-14 04:11 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +                        let jsonData = try jsonDecoder.decode(News.self, from: data)
前の構造体名がjsonDataだったので変数がその状態で残ってました！
構造体名を変えたらそれを入れる変数名も変えとかなだめですね笑

2021-01-14 04:12 UTC, Tech-Nayuta commented on CtaReactiveMaster/Resources/Base.lproj/LaunchScreen.storyboard
> +    <device id="retina6_1" orientation="portrait" appearance="light"/>
そうします笑

2021-01-14 04:58 UTC, takumaosada requested changes
最後細かいところだけ

2021-01-14 04:58 UTC, takumaosada commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +        if let url = URL(string: article.urlToImage ?? "") {
```suggestion
        if let urlString = article.urlToImage, let url = URL(string: urlString) {
```
方が良さそう

2021-01-14 04:58 UTC, takumaosada commented on CtaReactiveMaster/Sources/SceneDelegate.swift
> +            window.rootViewController = UINavigationController(rootViewController: HomeViewController(nibName: nil, bundle: nil))
```suggestion
            window.rootViewController = UINavigationController(rootViewController: HomeViewController())
```

2021-01-14 04:58 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +                    guard let data = data else{ return }
```suggestion
                    guard let data = data else { return }
```

2021-01-14 04:58 UTC, takumaosada commented on CtaReactiveMaster/Sources/AppDelegate.swift
> +        window.rootViewController = UINavigationController(rootViewController: HomeViewController(nibName: nil, bundle: nil))
```suggestion
        window.rootViewController = UINavigationController(rootViewController: HomeViewController())
```

2021-01-14 09:42 UTC, ry-itto requested changes
追加で 🙏🏼

2021-01-14 09:42 UTC, ry-itto commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    private func AfterFetch(){
関数は基本 lower camel で記述してほしい
```suggestion
    private func afterFetch(){
```

2021-01-14 09:42 UTC, ry-itto commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +
不要かな
```suggestion
```

2021-01-14 09:42 UTC, ry-itto commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +                    self.tableView.reloadData()
do の末尾に入れちゃってもいいかも

2021-01-14 09:42 UTC, ry-itto commented on CtaReactiveMaster/Sources/View/NewsTableViewCell.swift
> +        }
`if let` でキャプチャする変数の変数名は基本的に同じ名前の方がわかりやすいかも。この場合だと `publishedAt` とか
どちらにせよ、変数名に意味を持たせたいかな

2021-01-15 06:36 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +                    self.tableView.reloadData()
その方がいいですね

2021-01-15 07:52 UTC, takumaosada requested changes

2021-01-15 07:52 UTC, takumaosada commented on CtaReactiveMaster/Sources/Model/NewsApiJSON.swift
> +//
ファイル名もjson入ってるので修正必要そう

2021-01-15 07:52 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        guard let url = URL(string:articles[indexPath.row].url ?? "") else { return }
ここも`urlToImage`と同様の修正が必要

2021-01-16 05:12 UTC, takumaosada approved these changes
`APIClient`のファイルを作成してくれてると思うんだけどそれの対応は一旦このPRをmergeしてから別途作業してもらった方がなゆた的にもレビューする側的にもいいと思うんだけどどう？
(もしよければ`APIClient`のファイルを消去してもらえると:pray:)

2021-01-16 05:13 UTC, Tech-Nayuta commented
ああああわかりました！

2021-01-16 05:15 UTC, takumaosada commented
> ああああわかりました！

説明下手で申し訳ない！:bow:

2021-01-16 05:18 UTC, Tech-Nayuta commented
ちなみにプルリクがマージされる前に別の機能を実装をし始める（今回はAPIClient）場合はまた新しく枝を伸ばせばよかったですか？

2021-01-16 05:25 UTC, takumaosada commented
> ちなみにプルリクがマージされる前に別の機能を実装をし始める（今回はAPIClient）場合はまた新しく枝を伸ばせばよかったですか？

それで問題なさそう

2021-01-16 05:26 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        guard let url = URL(string:articles[indexPath.row].url ?? "") else { return }
修正完了しました！

2021-01-16 05:28 UTC, Tech-Nayuta commented
わかりました！ありがとうございます！
いまのところ修正は完了したのですがマージはまだしない方がいいですか？

2021-01-16 05:29 UTC, takumaosada commented
> わかりました！ありがとうございます！
> いまのところ修正は完了したのですがマージはまだしない方がいいですか？

なゆたのメインの21卒担当はりょうちゃんなのでりょうちゃんにもApproveをもらってからの方がいいと思う:ok_man:

2021-01-16 05:34 UTC, Tech-Nayuta commented
わかりました🙆‍♂️

2021-01-16 08:05 UTC, ry-itto approved these changes
LGTM 💯

2021-01-16 08:18 UTC, Tech-Nayuta commented
ありがとうございます！

2021-01-16 08:20 UTC, merged