Make APIClient
Tech-Nayuta/cta_reactive_master pull request #3
Opened 2021-01-18 07:44 UTC by Tech-Nayuta

[目的]
APIのリクエストをメソッドにして抽象化するため。

簡易的にですがAPIClientを作成しました。エンドポイントはtop-headlines,国はusで指定しています。
（reactive_master_answerの内容をほぼ参考にしました。）

2021-01-18 09:23 UTC, ry-itto requested changes
レビューしました 🙏🏼

2021-01-18 09:23 UTC, ry-itto commented on CtaReactiveMaster/Resources/Key.plist
> +</plist>
ignore できてないよ

2021-01-18 09:23 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/APIClient.swift
> +        print(request.url)
不要な print 文

2021-01-18 09:23 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/APIClient.swift
> +                    decoder.dateDecodingStrategy = .iso8601
わざわざ struct のプロパティレベルで decoder を定義しているので、関数の中で変更したくないかな

2021-01-18 09:23 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/APIClient.swift
> +                }
好みだけど、 `success` -> `failure` の方が自然かな

2021-01-18 09:23 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/APIClient.swift
> +                    return
不要な `return`

2021-01-18 09:23 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +enum Endpoint{
```suggestion
enum EndPoint {
```
かな？

どちらでも良いけど下のメソッドのケースと合わせたい

2021-01-18 09:23 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +        }
`EndPoint.topHeadlines.endPoint()` みたいなの、気持ち悪さあるので、
associated value 使ってエンドポイントの文字列をそのまま与えてもいいかも

2021-01-18 09:23 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +        }
`NewsAPIKey` と `newsAPIKey` どっちだろう？

2021-01-18 09:23 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +            fatalError("can't get filepath")
処理は停止するけどアプリがクラッシュします

2021-01-18 09:23 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +        guard let url = baseURL?.url else { fatalError("can't make url") }
ここで unwrap するくらいなら 序盤でしちゃおう

あと、 optional の unwrap で fatalError 使うと `!` 使うのと変わらないのであまりしない方がいいかな

2021-01-18 09:23 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/Requestable.swift
> +    var url: URL {get}
```suggestion
    var url: URL { get }
```

2021-01-18 09:23 UTC, ry-itto commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        //この時点ではresultの内容はわかっていないが奥深くにあるrequestメソッドでこのクロージャを使う際にそのrequestメソッドで引数を設定できる。
result の詳細な内容はわかってないけど、型レベルではわかってるって状態かな
closure 内で補完も効くし

2021-01-18 09:23 UTC, ry-itto commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        // ⇨ 別のリクエストをフェッチする際にクロージャの内容を変更できるようにするため
この closure は completion の closure なので、 API を叩いてそのレスポンスを使って何かをしたいときに渡す感じ

2021-01-18 09:24 UTC, Tech-Nayuta commented on CtaReactiveMaster/Resources/Key.plist
> +</plist>
あれ、ほんまですね...笑
APIキーの内容駄々漏れです😭

2021-01-18 09:24 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/APIClient/APIClient.swift
> +        print(request.url)
消しておきます！

2021-01-18 09:25 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/APIClient/APIClient.swift
> +                }
了解です！

2021-01-18 09:30 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +        guard let url = baseURL?.url else { fatalError("can't make url") }
了解です！
確かにクラッシュするなら!と一緒ですね...笑
ちなみに参考の方では  return baseURL.url! を使用されてるんですが、これはアンラップが確実に成功するからなのでしょうか？
また基本的にアンラップが確実に成功することがわかっている場合には ! をつけても大丈夫なのですか？

2021-01-18 10:28 UTC, nayutaroo commented on CtaReactiveMaster/Resources/Key.plist
> +</plist>
pushする前に git diffで確認しておけばよかったですね...笑

2021-01-18 10:28 UTC, nayutaroo commented on CtaReactiveMaster/Sources/APIClient/APIClient.swift
> +                    return
消します！

2021-01-18 10:28 UTC, nayutaroo commented on CtaReactiveMaster/Sources/APIClient/APIClient.swift
> +                    decoder.dateDecodingStrategy = .iso8601
たしかに定義した時点で設定できておいた方がいいですね

2021-01-18 10:28 UTC, nayutaroo commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +enum Endpoint{
了解です！

2021-01-18 10:28 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +        }
associated Value使ったパターン考えましたがあまりイメージできませんでした😢
シンプルにendPoint()の関数名をpath()にするのはどうですか？笑

2021-01-18 10:28 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +            fatalError("can't get filepath")
確かにそうですね...
クラッシュさせない処理をする場合はreturn文を使って結果を返すことになるとは思うのですが
その場合は空文字を返せばよいですか？
もしくはString?型にしてnilを返せば良いですか？（ただoptional型を用いると返した先でguard文つけるなどしてコードが長くなりそうなのでシンプルに気になりました）

2021-01-18 10:28 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +        }
NewsAPIKeyです。統一しときます。

2021-01-18 10:28 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        //この時点ではresultの内容はわかっていないが奥深くにあるrequestメソッドでこのクロージャを使う際にそのrequestメソッドで引数を設定できる。
型レベルでわかっているので closure中で.success .failureを使った処理ができるようなイメージですよね！

2021-01-18 10:28 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        // ⇨ 別のリクエストをフェッチする際にクロージャの内容を変更できるようにするため
なるほどですね！理解しました！

2021-01-18 10:35 UTC, Tech-Nayuta commented on CtaReactiveMaster/Resources/Key.plist
> +</plist>
シンプルにgitignoreでのパスの指定の仕方が間違っているんですかね....

2021-01-19 11:29 UTC, ry-itto commented on CtaReactiveMaster/Resources/Key.plist
> +</plist>
git ignore に追加してもgit のキャッシュに残っている場合があるので、 `git rm -r --cached .` とかしてから `git add` すると良いと思う

2021-01-19 11:41 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +        }
Associated Values を使っての書き方は

```swift
enum EndPoint: String {
  case topHeadlines = "/v2/top-headlines"
  ...
}
```

って定義して `EndPoint.topHeadlines.rawValue` で取得するイメージかな

2021-01-24 10:15 UTC, ry-itto requested changes
レビューしました 🙏🏼 
コードの書き方として統一感のないスペースなどあったので指摘してます(見逃しあるかもなので、まとめて修正してもらえると 🙏🏼

2021-01-24 10:15 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +            fatalError("can't get filepath")
いや、この場合、クラッシュで問題ないと思う
コメントで書いているのが勘違いしていたりしたらと思ってコメントした感じ

ファイルなかったらクラッシュは開発時に気づくはずなのでここでの fatalError はOKかな

2021-01-24 10:15 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +    var endpoint: Endpoint
var である必要ないかな　

2021-01-24 10:15 UTC, ry-itto commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    // Dependency Injection ( オブジェクトの注入 ）
言葉の訂正なんだけど、 Dependency Injection は日本語だと 依存性の注入ってよく紹介されているのでちょっと注意かな

やってることはその通りなんだけどね

2021-01-24 10:15 UTC, ry-itto commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        //この時点ではresultの内容はわかっていないが奥深くにあるrequestメソッドでこのクロージャを使う際にそのrequestメソッドで引数を設定できる。
そうだね、レスポンスもわかるので処理ができる

2021-01-24 10:15 UTC, ry-itto commented on CtaReactiveMaster/Sources/Repository/NewsRepository.swift
> +        let request = NewsAPIRequest(endpoint: .topHeadlines(.us,.technology))
```suggestion
        let request = NewsAPIRequest(endpoint: .topHeadlines(.us, .technology))
```

2021-01-24 10:15 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/APIClient.swift
> +    func request<T: Requestable>(_ request:T, completion: @escaping (Result<T.Response, NewsAPIError>) -> Void){
ここら辺統一しようか
```suggestion
    func request<T: Requestable>(_ request:T, completion: @escaping (Result<T.Response, NewsAPIError>) -> Void) {
```

2021-01-24 10:15 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/APIClient.swift
> +                catch let error{
```suggestion
                catch let error {
```

2021-01-24 10:15 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +    func path() -> String{
```suggestion
    func path() -> String {
```

2021-01-24 10:15 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +        guard let filePath = Bundle.main.path(forResource: "Key", ofType: "plist")  else{
```suggestion
        guard let filePath = Bundle.main.path(forResource: "Key", ofType: "plist")  else {
```

2021-01-24 10:15 UTC, ry-itto commented on CtaReactiveMaster/Sources/Extension/JSONDecoder+Extension.swift
> +extension JSONDecoder{
```suggestion
extension JSONDecoder {
```

2021-01-24 10:15 UTC, ry-itto commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    init(repository: NewsRepository){
```suggestion
    init(repository: NewsRepository) {
```

2021-01-24 10:15 UTC, ry-itto commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
>      private func afterFetch(){
```suggestion
    private func afterFetch() {
```

2021-01-25 02:53 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    // Dependency Injection ( オブジェクトの注入 ）
はい！その部分は分かった上で書いているので大丈夫です！

2021-01-25 02:58 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/APIClient/NewsAPIRequest.swift
> +    var endpoint: Endpoint
ほんまですね！変えときます

2021-01-25 03:01 UTC, Tech-Nayuta commented
修正しました！

2021-01-25 12:12 UTC, takumaosada approved these changes
不要なimport文は書かない方が良さそう
もしあれだったらFoundationが何を持ってて何を持ってないか調べてみてもいいかも

それ以外は良さそう！

2021-01-25 12:12 UTC, takumaosada commented on CtaReactiveMaster/Sources/APIClient/Requestable.swift
> +import Foundation
いらなそう

2021-01-25 12:12 UTC, takumaosada commented on CtaReactiveMaster/Sources/Entities/Category.swift
> +import Foundation
いらなそう

2021-01-25 12:12 UTC, takumaosada commented on CtaReactiveMaster/Sources/Entities/Country.swift
> +import Foundation
いらなそう

2021-01-26 03:02 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Entities/Country.swift
> +import Foundation
わかりました！
foundationは定型文のように考えてました笑
不要なimportをつけないのはimport処理に無駄な時間をかけないという認識であってますよね！

2021-01-26 03:05 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/APIClient/Requestable.swift
> +import Foundation
このファイルはURL型を使用しているのでFoundationないとエラーでてしまいます...

2021-01-26 03:08 UTC, Tech-Nayuta commented on CtaReactiveMaster/Sources/Entities/Country.swift
> +import Foundation
修正しました！

2021-02-11 12:13 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/APIClient.swift
> +    func request<T: Requestable>(_ request:T, completion: @escaping (Result<T.Response, NewsAPIError>) -> Void){
ここも

2021-02-11 12:13 UTC, ry-itto commented on CtaReactiveMaster/Sources/APIClient/APIClient.swift
> +                catch let error{
治ってないよー

2021-04-02 10:18 UTC, merged